const movieDetails = {
  adult: false,
  backdrop_path: "/2va32apQP97gvUxaMnL5wYt4CRB.jpg",
  belongs_to_collection: {
    id: 120794,
    name: "Batman Collection",
    poster_path: "/adQxUvQW8HXNsvMG5aj71pHh9T.jpg",
    backdrop_path: "/4UHZWw5lV3ZoadTjXuVOakdH32L.jpg",
  },
  budget: 35000000,
  genres: [
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 28,
      name: "Action",
    },
  ],
  homepage: "",
  id: 268,
  imdb_id: "tt0096895",
  original_language: "en",
  original_title: "Batman",
  overview:
    'Batman must face his most ruthless nemesis when a deformed madman calling himself "The Joker" seizes control of Gotham\'s criminal underworld.',
  popularity: 39.675,
  poster_path: "/r7XF6duZy5ZXmOX7HE3fKGV1WLN.jpg",
  production_companies: [
    {
      id: 9993,
      logo_path: "/2Tc1P3Ac8M479naPp1kYT3izLS5.png",
      name: "DC Entertainment",
      origin_country: "US",
    },
    {
      id: 429,
      logo_path: "/2Tc1P3Ac8M479naPp1kYT3izLS5.png",
      name: "DC Comics",
      origin_country: "US",
    },
    {
      id: 4357,
      logo_path: null,
      name: "The Guber-Peters Company",
      origin_country: "",
    },
    {
      id: 174,
      logo_path: "/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png",
      name: "Warner Bros. Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "GB",
      name: "United Kingdom",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "1989-06-23",
  revenue: 411348924,
  runtime: 126,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "French",
      iso_639_1: "fr",
      name: "Français",
    },
  ],
  status: "Released",
  tagline: "Have you ever danced with the devil in the pale moonlight?",
  title: "Batman",
  video: false,
  vote_average: 7.2,
  vote_count: 5643,
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 2232,
        known_for_department: "Acting",
        name: "Michael Keaton",
        original_name: "Michael Keaton",
        popularity: 10.186,
        profile_path: "/baeHNv3qrVsnApuKbZXiJOhqMnw.jpg",
        cast_id: 4,
        character: "Bruce Wayne / Batman",
        credit_id: "52fe422fc3a36847f800aa01",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 514,
        known_for_department: "Acting",
        name: "Jack Nicholson",
        original_name: "Jack Nicholson",
        popularity: 10.567,
        profile_path: "/sX2eryfpUdlGsZOzoDlszmQYyPP.jpg",
        cast_id: 5,
        character: "Jack Napier / The Joker",
        credit_id: "52fe422fc3a36847f800aa05",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 326,
        known_for_department: "Acting",
        name: "Kim Basinger",
        original_name: "Kim Basinger",
        popularity: 7.279,
        profile_path: "/iqQ4o2sRna7J1Z9KkB9Avp9CIsk.jpg",
        cast_id: 6,
        character: "Vicki Vale",
        credit_id: "52fe422fc3a36847f800aa09",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 4040,
        known_for_department: "Acting",
        name: "Robert Wuhl",
        original_name: "Robert Wuhl",
        popularity: 2.757,
        profile_path: "/uPLdA7NX6YLpAACoBHZ91a8V75I.jpg",
        cast_id: 24,
        character: "Alexander Knox",
        credit_id: "52fe4230c3a36847f800aa61",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 3798,
        known_for_department: "Acting",
        name: "Pat Hingle",
        original_name: "Pat Hingle",
        popularity: 7.619,
        profile_path: "/QBAxFVZQ0Hu6rxlFavhwUq0zug.jpg",
        cast_id: 8,
        character: "Commissioner James Gordon",
        credit_id: "52fe422fc3a36847f800aa11",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 3799,
        known_for_department: "Acting",
        name: "Billy Dee Williams",
        original_name: "Billy Dee Williams",
        popularity: 2.438,
        profile_path: "/dCiHLiCapPuRwKkM1ytVZ7PwYQY.jpg",
        cast_id: 9,
        character: "Harvey Dent",
        credit_id: "52fe422fc3a36847f800aa15",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 3796,
        known_for_department: "Acting",
        name: "Michael Gough",
        original_name: "Michael Gough",
        popularity: 2.005,
        profile_path: "/owcwnV6dymBd9YIQKDPzVA5EtZX.jpg",
        cast_id: 7,
        character: "Alfred Pennyworth",
        credit_id: "52fe422fc3a36847f800aa0d",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 3785,
        known_for_department: "Acting",
        name: "Jack Palance",
        original_name: "Jack Palance",
        popularity: 2.886,
        profile_path: "/sRr2YPa1IElRE1vG1PQcgLrS9om.jpg",
        cast_id: 10,
        character: "Carl Grissom",
        credit_id: "52fe422fc3a36847f800aa19",
        order: 7,
      },
      {
        adult: false,
        gender: 1,
        id: 3800,
        known_for_department: "Acting",
        name: "Jerry Hall",
        original_name: "Jerry Hall",
        popularity: 0.84,
        profile_path: "/kInkl0xOfRhzA0x72JjIA5w2ugt.jpg",
        cast_id: 11,
        character: "Alicia Grissom",
        credit_id: "52fe422fc3a36847f800aa1d",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 3801,
        known_for_department: "Acting",
        name: "Tracey Walter",
        original_name: "Tracey Walter",
        popularity: 1.847,
        profile_path: "/9aALfdCcP0PDYcBmqB6auHF0Eud.jpg",
        cast_id: 12,
        character: "Bob the Goon",
        credit_id: "52fe422fc3a36847f800aa21",
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 3802,
        known_for_department: "Acting",
        name: "Lee Wallace",
        original_name: "Lee Wallace",
        popularity: 1.686,
        profile_path: null,
        cast_id: 13,
        character: "Mayor",
        credit_id: "52fe422fc3a36847f800aa25",
        order: 10,
      },
      {
        adult: false,
        gender: 2,
        id: 663,
        known_for_department: "Acting",
        name: "William Hootkins",
        original_name: "William Hootkins",
        popularity: 1.634,
        profile_path: "/dav2i86GN0UvYIyoTwQmGE8Nweg.jpg",
        cast_id: 14,
        character: "Eckhardt",
        credit_id: "52fe422fc3a36847f800aa29",
        order: 11,
      },
      {
        adult: false,
        gender: 2,
        id: 79502,
        known_for_department: "Acting",
        name: "Richard Strange",
        original_name: "Richard Strange",
        popularity: 1.38,
        profile_path: "/f7QFUkwkqyegwUIFKarU4ahz3Ku.jpg",
        cast_id: 27,
        character: "Goon",
        credit_id: "58932a45c3a3686d17004caf",
        order: 12,
      },
      {
        adult: false,
        gender: 2,
        id: 127166,
        known_for_department: "Acting",
        name: "Carl Chase",
        original_name: "Carl Chase",
        popularity: 1.548,
        profile_path: null,
        cast_id: 95,
        character: "Goon",
        credit_id: "5bbe9fcbc3a3682b46003da4",
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 33403,
        known_for_department: "Acting",
        name: "Mac McDonald",
        original_name: "Mac McDonald",
        popularity: 3.113,
        profile_path: "/gejehuptBzsJlPiWKU8B9TTrc7r.jpg",
        cast_id: 130,
        character: "Goon",
        credit_id: "5bbea4199251413d60004923",
        order: 14,
      },
      {
        adult: false,
        gender: 2,
        id: 1806344,
        known_for_department: "Acting",
        name: "George Lane Cooper",
        original_name: "George Lane Cooper",
        popularity: 1.528,
        profile_path: null,
        cast_id: 97,
        character: "Goon",
        credit_id: "5bbea0059251413d51004839",
        order: 15,
      },
      {
        adult: false,
        gender: 2,
        id: 1229878,
        known_for_department: "Acting",
        name: "Terence Plummer",
        original_name: "Terence Plummer",
        popularity: 0.994,
        profile_path: "/njEgNWH0AdcNAPShEPp9gNhrj7F.jpg",
        cast_id: 98,
        character: "Goon",
        credit_id: "5bbea0139251413d650042e8",
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 702,
        known_for_department: "Acting",
        name: "Philip Tan",
        original_name: "Philip Tan",
        popularity: 1.4,
        profile_path: "/6cXDkOsHPbdsgiUUM7UIz6s8cXX.jpg",
        cast_id: 99,
        character: "Goon",
        credit_id: "5bbea020c3a36844fe001115",
        order: 17,
      },
      {
        adult: false,
        gender: 0,
        id: 1231674,
        known_for_department: "Acting",
        name: "John Sterland",
        original_name: "John Sterland",
        popularity: 0.6,
        profile_path: null,
        cast_id: 100,
        character: "Accountant",
        credit_id: "5bbea08f0e0a26249c00118e",
        order: 18,
      },
      {
        adult: false,
        gender: 0,
        id: 3803,
        known_for_department: "Acting",
        name: "Edwin Craig",
        original_name: "Edwin Craig",
        popularity: 0.786,
        profile_path: null,
        cast_id: 15,
        character: "Rotelli",
        credit_id: "52fe422fc3a36847f800aa2d",
        order: 19,
      },
      {
        adult: false,
        gender: 2,
        id: 1257821,
        known_for_department: "Acting",
        name: "Vincent Wong",
        original_name: "Vincent Wong",
        popularity: 0.6,
        profile_path: "/lWPw6iMQKOSh4w099GkexZKkv4F.jpg",
        cast_id: 26,
        character: "Crimelord #1",
        credit_id: "57f8030e92514116aa000cc6",
        order: 20,
      },
      {
        adult: false,
        gender: 0,
        id: 929078,
        known_for_department: "Acting",
        name: "Joel Cutrara",
        original_name: "Joel Cutrara",
        popularity: 0.6,
        profile_path: null,
        cast_id: 101,
        character: "Crimelord #2",
        credit_id: "5bbea0a30e0a26249c0011aa",
        order: 21,
      },
      {
        adult: false,
        gender: 0,
        id: 1348858,
        known_for_department: "Acting",
        name: "John Dair",
        original_name: "John Dair",
        popularity: 0.6,
        profile_path: null,
        cast_id: 102,
        character: "Ricorso",
        credit_id: "5bbea0bc0e0a262366004bcf",
        order: 22,
      },
      {
        adult: false,
        gender: 2,
        id: 8399,
        known_for_department: "Acting",
        name: "Christopher Fairbank",
        original_name: "Christopher Fairbank",
        popularity: 3.58,
        profile_path: "/6bO8JmhkC0GzU4gIBdSMY48E3CD.jpg",
        cast_id: 28,
        character: "Nic",
        credit_id: "58932a649251416eeb0047de",
        order: 23,
      },
      {
        adult: false,
        gender: 2,
        id: 2147290,
        known_for_department: "Acting",
        name: "George Roth",
        original_name: "George Roth",
        popularity: 0.6,
        profile_path: null,
        cast_id: 103,
        character: "Eddie",
        credit_id: "5bbea0cc0e0a26236f004e4f",
        order: 24,
      },
      {
        adult: false,
        gender: 1,
        id: 1497048,
        known_for_department: "Acting",
        name: "Kate Harper",
        original_name: "Kate Harper",
        popularity: 1.4,
        profile_path: "/uN0CA2CsywCU3ZUbZBEOCwqS8lQ.jpg",
        cast_id: 104,
        character: "Anchorwoman",
        credit_id: "5bbea0da0e0a26236f004e6d",
        order: 25,
      },
      {
        adult: false,
        gender: 2,
        id: 100654,
        known_for_department: "Acting",
        name: "Bruce McGuire",
        original_name: "Bruce McGuire",
        popularity: 0.6,
        profile_path: "/mdy1CIIAtvWvEsGY1qOook98VKb.jpg",
        cast_id: 166,
        character: "Anchorman",
        credit_id: "609ae7f4764841003ae384e9",
        order: 26,
      },
      {
        adult: false,
        gender: 2,
        id: 120833,
        known_for_department: "Acting",
        name: "Richard Durden",
        original_name: "Richard Durden",
        popularity: 1.62,
        profile_path: "/eH5gdjtoCMFNs2OlSyWb0ha2yHn.jpg",
        cast_id: 29,
        character: "TV Director",
        credit_id: "58932a739251416ef8004e1f",
        order: 27,
      },
      {
        adult: false,
        gender: 0,
        id: 2147293,
        known_for_department: "Acting",
        name: "Kit Hollerbach",
        original_name: "Kit Hollerbach",
        popularity: 0.6,
        profile_path: null,
        cast_id: 106,
        character: "Becky",
        credit_id: "5bbea17a9251413d5900462d",
        order: 28,
      },
      {
        adult: false,
        gender: 0,
        id: 2147294,
        known_for_department: "Acting",
        name: "Lachelle Carl",
        original_name: "Lachelle Carl",
        popularity: 0.6,
        profile_path: null,
        cast_id: 107,
        character: "TV Technician",
        credit_id: "5bbea188c3a3682b46004018",
        order: 29,
      },
      {
        adult: false,
        gender: 2,
        id: 1717052,
        known_for_department: "Acting",
        name: "Del Baker",
        original_name: "Del Baker",
        popularity: 0.6,
        profile_path: "/qFfE9Dx3nimQdb0eDsfO1XTy05B.jpg",
        cast_id: 108,
        character: "Napier Hood #1",
        credit_id: "5bbea19a0e0a262366004d48",
        order: 30,
      },
      {
        adult: false,
        gender: 0,
        id: 1534130,
        known_for_department: "Crew",
        name: "Jazzer Jeyes",
        original_name: "Jazzer Jeyes",
        popularity: 0.6,
        profile_path: null,
        cast_id: 109,
        character: "Napier Hood #2",
        credit_id: "5bbea1ae0e0a26249f001320",
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 1469954,
        known_for_department: "Acting",
        name: "Wayne Michaels",
        original_name: "Wayne Michaels",
        popularity: 0.6,
        profile_path: null,
        cast_id: 110,
        character: "Napier Hood #3",
        credit_id: "5bbea1c20e0a26249f001337",
        order: 32,
      },
      {
        adult: false,
        gender: 2,
        id: 1229882,
        known_for_department: "Acting",
        name: "Valentino Musetti",
        original_name: "Valentino Musetti",
        popularity: 0.6,
        profile_path: null,
        cast_id: 111,
        character: "Napier Hood #4",
        credit_id: "5bbea1d10e0a2624c6001241",
        order: 33,
      },
      {
        adult: false,
        gender: 2,
        id: 40740,
        known_for_department: "Crew",
        name: "Rocky Taylor",
        original_name: "Rocky Taylor",
        popularity: 0.6,
        profile_path: null,
        cast_id: 112,
        character: "Napier Hood #5",
        credit_id: "5bbea1e69251413d59004810",
        order: 34,
      },
      {
        adult: false,
        gender: 2,
        id: 2099757,
        known_for_department: "Acting",
        name: "Keith Edwards",
        original_name: "Keith Edwards",
        popularity: 0.6,
        profile_path: null,
        cast_id: 113,
        character: "Reporter",
        credit_id: "5bbea1f30e0a26236f004fcd",
        order: 35,
      },
      {
        adult: false,
        gender: 2,
        id: 145536,
        known_for_department: "Acting",
        name: "Leon Herbert",
        original_name: "Leon Herbert",
        popularity: 0.703,
        profile_path: null,
        cast_id: 114,
        character: "Reporter",
        credit_id: "5bbea2010e0a26249c001430",
        order: 36,
      },
      {
        adult: false,
        gender: 2,
        id: 140148,
        known_for_department: "Acting",
        name: "Steve Plytas",
        original_name: "Steve Plytas",
        popularity: 2.806,
        profile_path: "/qFGSjfiC6qBEMCdpvZgI4YIUvE4.jpg",
        cast_id: 31,
        character: "Doctor",
        credit_id: "598643679251413d39006b53",
        order: 37,
      },
      {
        adult: false,
        gender: 0,
        id: 2147295,
        known_for_department: "Acting",
        name: "Anthony Wellington",
        original_name: "Anthony Wellington",
        popularity: 0.6,
        profile_path: null,
        cast_id: 115,
        character: "Patrolman at Party",
        credit_id: "5bbea26a0e0a26249c0014a7",
        order: 38,
      },
      {
        adult: false,
        gender: 2,
        id: 231299,
        known_for_department: "Acting",
        name: "Amir M. Korangy",
        original_name: "Amir M. Korangy",
        popularity: 0.973,
        profile_path: "/kMT5dZ2BN7pFz3Y9elSLRlthiWz.jpg",
        cast_id: 116,
        character: "Wine Steward",
        credit_id: "5bbea27b0e0a26249c0014ca",
        order: 39,
      },
      {
        adult: false,
        gender: 2,
        id: 218373,
        known_for_department: "Production",
        name: "Hugo Blick",
        original_name: "Hugo Blick",
        popularity: 0.6,
        profile_path: null,
        cast_id: 32,
        character: "Young Jack Napier",
        credit_id: "5a497641c3a36805c5004c77",
        order: 40,
      },
      {
        adult: false,
        gender: 0,
        id: 2147297,
        known_for_department: "Acting",
        name: "Charles Roskilly",
        original_name: "Charles Roskilly",
        popularity: 0.6,
        profile_path: null,
        cast_id: 117,
        character: "Young Bruce Wayne",
        credit_id: "5bbea28d92514179a4001219",
        order: 41,
      },
      {
        adult: false,
        gender: 2,
        id: 987040,
        known_for_department: "Acting",
        name: "Philip O'Brien",
        original_name: "Philip O'Brien",
        popularity: 0.6,
        profile_path: null,
        cast_id: 118,
        character: "Maitre d'",
        credit_id: "5bbea29f9251413d590048ab",
        order: 42,
      },
      {
        adult: false,
        gender: 2,
        id: 18763,
        known_for_department: "Acting",
        name: "Michael Balfour",
        original_name: "Michael Balfour",
        popularity: 0.6,
        profile_path: "/uLybbsWryAsc7gZ0CDIY8V34HRT.jpg",
        cast_id: 119,
        character: "Scientist",
        credit_id: "5bbea2af0e0a2624c60013d0",
        order: 43,
      },
      {
        adult: false,
        gender: 2,
        id: 17356,
        known_for_department: "Acting",
        name: "Garrick Hagon",
        original_name: "Garrick Hagon",
        popularity: 0.899,
        profile_path: "/lDtVxw5eMfmexYgL6OZJTfSCRCN.jpg",
        cast_id: 94,
        character: "Dad",
        credit_id: "5b3199d79251413c890073ee",
        order: 44,
      },
      {
        adult: false,
        gender: 1,
        id: 1738564,
        known_for_department: "Acting",
        name: "Liza Ross",
        original_name: "Liza Ross",
        popularity: 0.6,
        profile_path: null,
        cast_id: 120,
        character: "Mom",
        credit_id: "5bbea2ba9251413d51004c16",
        order: 45,
      },
      {
        adult: false,
        gender: 0,
        id: 2147298,
        known_for_department: "Acting",
        name: "Adrian Meyers",
        original_name: "Adrian Meyers",
        popularity: 0.6,
        profile_path: null,
        cast_id: 121,
        character: "Jimmy",
        credit_id: "5bbea2c60e0a26235f0045ed",
        order: 46,
      },
      {
        adult: false,
        gender: 0,
        id: 38651,
        known_for_department: "Acting",
        name: "David Baxt",
        original_name: "David Baxt",
        popularity: 1.052,
        profile_path: "/amzGafV7re5W1Xxnsj0L52eZiIy.jpg",
        cast_id: 122,
        character: "Dr Wayne",
        credit_id: "5bbea2d2c3a3682b3400578f",
        order: 47,
      },
      {
        adult: false,
        gender: 0,
        id: 2147300,
        known_for_department: "Acting",
        name: "Sharon Holm",
        original_name: "Sharon Holm",
        popularity: 0.6,
        profile_path: null,
        cast_id: 123,
        character: "Mrs Wayne",
        credit_id: "5bbea32b0e0a26236f00511e",
        order: 48,
      },
      {
        adult: false,
        gender: 0,
        id: 2147301,
        known_for_department: "Acting",
        name: "Clyde Gatell",
        original_name: "Clyde Gatell",
        popularity: 0.6,
        profile_path: null,
        cast_id: 124,
        character: "Other Mugger",
        credit_id: "5bbea3419251413d5900498e",
        order: 49,
      },
      {
        adult: false,
        gender: 0,
        id: 2147302,
        known_for_department: "Acting",
        name: "Jon Soresi",
        original_name: "Jon Soresi",
        popularity: 0.6,
        profile_path: null,
        cast_id: 125,
        character: "Medic",
        credit_id: "5bbea34d0e0a262359004dc1",
        order: 50,
      },
      {
        adult: false,
        gender: 0,
        id: 1164393,
        known_for_department: "Writing",
        name: "Elliott Stein",
        original_name: "Elliott Stein",
        popularity: 0.6,
        profile_path: null,
        cast_id: 126,
        character: "Man in Crowd",
        credit_id: "5bbea35e0e0a26232b001495",
        order: 51,
      },
      {
        adult: false,
        gender: 2,
        id: 17072,
        known_for_department: "Acting",
        name: "Sam Douglas",
        original_name: "Sam Douglas",
        popularity: 0.955,
        profile_path: "/hGtVDo5BF4utyCbrEUm3RDNA28B.jpg",
        cast_id: 30,
        character: "Lawyer",
        credit_id: "58932a8bc3a3686d1c004b39",
        order: 52,
      },
      {
        adult: false,
        gender: 2,
        id: 129452,
        known_for_department: "Acting",
        name: "Denis Lill",
        original_name: "Denis Lill",
        popularity: 0.98,
        profile_path: "/9tbJGo2OC4dzr8Mpk3QM0sMfdMb.jpg",
        cast_id: 127,
        character: "Bob Kane",
        credit_id: "5bbea370c3a3682b4b00480b",
        order: 53,
      },
      {
        adult: false,
        gender: 2,
        id: 29617,
        known_for_department: "Acting",
        name: "Paul Birchard",
        original_name: "Paul Birchard",
        popularity: 0.6,
        profile_path: "/3A8JwCXwIE3qYwaFLFyaixUp070.jpg",
        cast_id: 128,
        character: "Reporter",
        credit_id: "5bbea3800e0a262359004e0a",
        order: 54,
      },
      {
        adult: false,
        gender: 0,
        id: 1744217,
        known_for_department: "Acting",
        name: "Paul Michael",
        original_name: "Paul Michael",
        popularity: 0.6,
        profile_path: null,
        cast_id: 129,
        character: "Cop",
        credit_id: "5bbea39292514179a400138b",
        order: 55,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 244,
        known_for_department: "Editing",
        name: "Ray Lovejoy",
        original_name: "Ray Lovejoy",
        popularity: 1.4,
        profile_path: null,
        credit_id: "52fe422fc3a36847f800aa4b",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 293,
        known_for_department: "Camera",
        name: "Roger Pratt",
        original_name: "Roger Pratt",
        popularity: 0.6,
        profile_path: null,
        credit_id: "52fe422fc3a36847f800aa3f",
        department: "Camera",
        job: "Director of Photography",
      },
      {
        adult: false,
        gender: 2,
        id: 510,
        known_for_department: "Directing",
        name: "Tim Burton",
        original_name: "Tim Burton",
        popularity: 7.559,
        profile_path: "/gRM4lGpiBINAyiXaxEeJFDKzmge.jpg",
        credit_id: "52fe422fc3a36847f800a9f1",
        department: "Directing",
        job: "Director",
      },
      {
        adult: false,
        gender: 2,
        id: 531,
        known_for_department: "Sound",
        name: "Danny Elfman",
        original_name: "Danny Elfman",
        popularity: 1.056,
        profile_path: "/zFladKAPypbzp26Tfyeiy23vanH.jpg",
        credit_id: "52fe422fc3a36847f800aa45",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 0,
        id: 913,
        known_for_department: "Writing",
        name: "Warren Skaaren",
        original_name: "Warren Skaaren",
        popularity: 0.84,
        profile_path: null,
        credit_id: "52fe422fc3a36847f800a9fd",
        department: "Writing",
        job: "Screenplay",
      },
      {
        adult: false,
        gender: 2,
        id: 2530,
        known_for_department: "Costume & Make-Up",
        name: "Bob Ringwood",
        original_name: "Bob Ringwood",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccddf9251411ea7022da4",
        department: "Costume & Make-Up",
        job: "Costume Design",
      },
      {
        adult: false,
        gender: 2,
        id: 3794,
        known_for_department: "Writing",
        name: "Bob Kane",
        original_name: "Bob Kane",
        popularity: 2.794,
        profile_path: "/vuXwrlqaUydA4t5SFVdQkK9KsZL.jpg",
        credit_id: "52fe422fc3a36847f800a9f7",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 2,
        id: 3804,
        known_for_department: "Production",
        name: "Peter Guber",
        original_name: "Peter Guber",
        popularity: 0.6,
        profile_path: "/6QILn3KDqoJrRMz8rRzTYS3igCc.jpg",
        credit_id: "52fe422fc3a36847f800aa33",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 3805,
        known_for_department: "Production",
        name: "Jon Peters",
        original_name: "Jon Peters",
        popularity: 0.75,
        profile_path: "/ts4JBYG2LEbquRzExGHer1122AI.jpg",
        credit_id: "52fe422fc3a36847f800aa39",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 3806,
        known_for_department: "Production",
        name: "Marion Dougherty",
        original_name: "Marion Dougherty",
        popularity: 0.6,
        profile_path: null,
        credit_id: "52fe422fc3a36847f800aa51",
        department: "Production",
        job: "Casting",
      },
      {
        adult: false,
        gender: 2,
        id: 3807,
        known_for_department: "Art",
        name: "Anton Furst",
        original_name: "Anton Furst",
        popularity: 0.652,
        profile_path: null,
        credit_id: "52fe4230c3a36847f800aa57",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 2,
        id: 3795,
        known_for_department: "Writing",
        name: "Sam Hamm",
        original_name: "Sam Hamm",
        popularity: 1.96,
        profile_path: null,
        credit_id: "52fe4230c3a36847f800aa5d",
        department: "Writing",
        job: "Screenplay",
      },
      {
        adult: false,
        gender: 0,
        id: 5021,
        known_for_department: "Art",
        name: "Leslie Tomkins",
        original_name: "Leslie Tomkins",
        popularity: 1.052,
        profile_path: null,
        credit_id: "5abccdb19251411e920245c4",
        department: "Art",
        job: "Supervising Art Director",
      },
      {
        adult: false,
        gender: 2,
        id: 5132,
        known_for_department: "Sound",
        name: "Bob Badami",
        original_name: "Bob Badami",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd209c3a368435f022dcd",
        department: "Sound",
        job: "Music Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 10949,
        known_for_department: "Production",
        name: "Michael Uslan",
        original_name: "Michael Uslan",
        popularity: 1.429,
        profile_path: "/cXiiH0SSk5UHCvHOVAhHX7tNuls.jpg",
        credit_id: "570ede8992514102af000bff",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 10951,
        known_for_department: "Production",
        name: "Benjamin Melniker",
        original_name: "Benjamin Melniker",
        popularity: 1.4,
        profile_path: null,
        credit_id: "5abccd54c3a36843620244ec",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 8418,
        known_for_department: "Production",
        name: "Suzie F. Wiesmann",
        original_name: "Suzie F. Wiesmann",
        popularity: 0.679,
        profile_path: null,
        credit_id: "5cef09f6c3a368637f1e3ca3",
        department: "Visual Effects",
        job: "Visual Effects Production Manager",
      },
      {
        adult: false,
        gender: 2,
        id: 9817,
        known_for_department: "Art",
        name: "Nigel Phelps",
        original_name: "Nigel Phelps",
        popularity: 1.4,
        profile_path: null,
        credit_id: "5abccd929251411ea0023ffc",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 9823,
        known_for_department: "Art",
        name: "Peter Young",
        original_name: "Peter Young",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccdc70e0a2609de02578c",
        department: "Art",
        job: "Set Decoration",
      },
      {
        adult: false,
        gender: 2,
        id: 11173,
        known_for_department: "Costume & Make-Up",
        name: "Nick Dudman",
        original_name: "Nick Dudman",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccf3a9251411ea7022ecd",
        department: "Costume & Make-Up",
        job: "Makeup Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 11348,
        known_for_department: "Costume & Make-Up",
        name: "Lynda Armstrong",
        original_name: "Lynda Armstrong",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccf270e0a2609d20251f3",
        department: "Costume & Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 10200,
        known_for_department: "Art",
        name: "Terry Ackland-Snow",
        original_name: "Terry Ackland-Snow",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccd7dc3a368436202450f",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 1,
        id: 11459,
        known_for_department: "Production",
        name: "Sally Osoba",
        original_name: "Sally Osoba",
        popularity: 0.656,
        profile_path: null,
        credit_id: "5cef0a6892514109b5b896bf",
        department: "Production",
        job: "Casting Assistant",
      },
      {
        adult: false,
        gender: 2,
        id: 12761,
        known_for_department: "Sound",
        name: "Eddy Joseph",
        original_name: "Eddy Joseph",
        popularity: 0.6,
        profile_path: "/mvYjNzo1G0FyQnj0Ka6yLbDqjPZ.jpg",
        credit_id: "5abcd2640e0a2609d5026f70",
        department: "Sound",
        job: "Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 16589,
        known_for_department: "Directing",
        name: "Peter MacDonald",
        original_name: "Peter MacDonald",
        popularity: 4.002,
        profile_path: "/sulOWgN2WZKDOlg8JMpTv8TUSHh.jpg",
        credit_id: "5c8afee10e0a260420c55d8e",
        department: "Directing",
        job: "Second Unit Director",
      },
      {
        adult: false,
        gender: 0,
        id: 18759,
        known_for_department: "Crew",
        name: "Charles Staffell",
        original_name: "Charles Staffell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccf969251411e92024755",
        department: "Crew",
        job: "Projection",
      },
      {
        adult: false,
        gender: 0,
        id: 20110,
        known_for_department: "Sound",
        name: "Don Sharpe",
        original_name: "Don Sharpe",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd2890e0a2609e4025911",
        department: "Sound",
        job: "Supervising Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 21037,
        known_for_department: "Acting",
        name: "Prince",
        original_name: "Prince",
        popularity: 0.6,
        profile_path: "/5HPqjSXEQukk6ta8v1i9mPHUeqk.jpg",
        credit_id: "5e49ba1f35811d001948b72a",
        department: "Sound",
        job: "Songs",
      },
      {
        adult: false,
        gender: 1,
        id: 26981,
        known_for_department: "Sound",
        name: "Shirley Walker",
        original_name: "Shirley Walker",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0aa792514109b5b8987d",
        department: "Sound",
        job: "Conductor",
      },
      {
        adult: false,
        gender: 2,
        id: 38335,
        known_for_department: "Sound",
        name: "Steve Bartek",
        original_name: "Steve Bartek",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd230c3a3687cb701c93a",
        department: "Sound",
        job: "Orchestrator",
      },
      {
        adult: false,
        gender: 0,
        id: 71130,
        known_for_department: "Sound",
        name: "Michael Dilbeck",
        original_name: "Michael Dilbeck",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd21bc3a36843790263ec",
        department: "Sound",
        job: "Music Supervisor",
      },
      {
        adult: false,
        gender: 2,
        id: 63064,
        known_for_department: "Camera",
        name: "Ali Asad",
        original_name: "Ali Asad",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a2d9251410fe2b9fec7",
        department: "Camera",
        job: "Assistant Camera",
      },
      {
        adult: false,
        gender: 2,
        id: 71579,
        known_for_department: "Art",
        name: "David Allday",
        original_name: "David Allday",
        popularity: 1.22,
        profile_path: null,
        credit_id: "5cef097e0e0a264555ca103b",
        department: "Art",
        job: "Draughtsman",
      },
      {
        adult: false,
        gender: 0,
        id: 75783,
        known_for_department: "Production",
        name: "Gordon Arnell",
        original_name: "Gordon Arnell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1cd9251411e9a02395b",
        department: "Production",
        job: "Publicist",
      },
      {
        adult: false,
        gender: 2,
        id: 198034,
        known_for_department: "Writing",
        name: "Bill Finger",
        original_name: "Bill Finger",
        popularity: 2.867,
        profile_path: "/2gmiO0SX9wkY6LS9z9zrthyPeJl.jpg",
        credit_id: "5fe9df095b1240003c6cd101",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 0,
        id: 227557,
        known_for_department: "Visual Effects",
        name: "Derek Meddings",
        original_name: "Derek Meddings",
        popularity: 1.214,
        profile_path: null,
        credit_id: "5e2f0a01fd140b00196bd3d5",
        department: "Visual Effects",
        job: "Visual Effects",
      },
      {
        adult: false,
        gender: 2,
        id: 1077325,
        known_for_department: "Acting",
        name: "Eddie Powell",
        original_name: "Eddie Powell",
        popularity: 1.96,
        profile_path: null,
        credit_id: "5f3059b9f1b5710036eba48c",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 2,
        id: 1185530,
        known_for_department: "Crew",
        name: "Eddie Stacey",
        original_name: "Eddie Stacey",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd011c3a368435f022c41",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 1323295,
        known_for_department: "Costume & Make-Up",
        name: "Graham Churchyard",
        original_name: "Graham Churchyard",
        popularity: 0.714,
        profile_path: null,
        credit_id: "5abccedfc3a3684388027ce6",
        department: "Costume & Make-Up",
        job: "Assistant Costume Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 1326461,
        known_for_department: "Costume & Make-Up",
        name: "Annie Crawford",
        original_name: "Annie Crawford",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a940e0a2615b5cb92ca",
        department: "Costume & Make-Up",
        job: "Wardrobe Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1342592,
        known_for_department: "Crew",
        name: "Brian Bishop",
        original_name: "Brian Bishop",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccfd90e0a2609e1026e57",
        department: "Crew",
        job: "Scenic Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 1373728,
        known_for_department: "Lighting",
        name: "Chuck Finch",
        original_name: "Chuck Finch",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd14e0e0a2609de025acf",
        department: "Lighting",
        job: "Gaffer",
      },
      {
        adult: false,
        gender: 0,
        id: 1392245,
        known_for_department: "Camera",
        name: "Murray Close",
        original_name: "Murray Close",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccec9c3a368435c02665a",
        department: "Camera",
        job: "Still Photographer",
      },
      {
        adult: false,
        gender: 0,
        id: 1393300,
        known_for_department: "Sound",
        name: "Jack Stew",
        original_name: "Jack Stew",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef09bb0e0a2613cdcb8f70",
        department: "Sound",
        job: "Foley Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 1393335,
        known_for_department: "Lighting",
        name: "Billy Merrell",
        original_name: "Billy Merrell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd11f9251411e9a0238bd",
        department: "Lighting",
        job: "Best Boy Electric",
      },
      {
        adult: false,
        gender: 0,
        id: 1394777,
        known_for_department: "Art",
        name: "Charles Torbett",
        original_name: "Charles Torbett",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccfc69251411ea3024963",
        department: "Art",
        job: "Property Master",
      },
      {
        adult: false,
        gender: 0,
        id: 1395729,
        known_for_department: "Sound",
        name: "Tony Dawe",
        original_name: "Tony Dawe",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd244c3a3684379026417",
        department: "Sound",
        job: "Production Sound Mixer",
      },
      {
        adult: false,
        gender: 0,
        id: 1406920,
        known_for_department: "Visual Effects",
        name: "Eddie Butler",
        original_name: "Eddie Butler",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcce649251411ea00240cf",
        department: "Art",
        job: "Sculptor",
      },
      {
        adult: false,
        gender: 0,
        id: 1408796,
        known_for_department: "Production",
        name: "Chris Brock",
        original_name: "Chris Brock",
        popularity: 0.694,
        profile_path: null,
        credit_id: "5abcd1840e0a2609db026ace",
        department: "Production",
        job: "Location Manager",
      },
      {
        adult: false,
        gender: 0,
        id: 1417831,
        known_for_department: "Crew",
        name: "Sy Hollands",
        original_name: "Sy Hollands",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a0d925141099fb89c2e",
        department: "Crew",
        job: "Stunt Double",
      },
      {
        adult: false,
        gender: 2,
        id: 1424180,
        known_for_department: "Camera",
        name: "Jonathan Taylor",
        original_name: "Jonathan Taylor",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a560e0a2636a5cb818c",
        department: "Camera",
        job: "Focus Puller",
      },
      {
        adult: false,
        gender: 2,
        id: 1513635,
        known_for_department: "Directing",
        name: "Derek Cracknell",
        original_name: "Derek Cracknell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd050c3a3684379026245",
        department: "Directing",
        job: "First Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 1524299,
        known_for_department: "Directing",
        name: "Cheryl Leigh",
        original_name: "Cheryl Leigh",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd0d2c3a36843a6026f90",
        department: "Directing",
        job: "Script Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1543759,
        known_for_department: "Lighting",
        name: "Bernie Hagadorn",
        original_name: "Bernie Hagadorn",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd175c3a3684396026d20",
        department: "Lighting",
        job: "Rigging Grip",
      },
      {
        adult: false,
        gender: 0,
        id: 1567968,
        known_for_department: "Art",
        name: "Chris Buchinsky",
        original_name: "Chris Buchinsky",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd373c3a3684362024a5f",
        department: "Writing",
        job: "Storyboard",
      },
      {
        adult: false,
        gender: 0,
        id: 1592616,
        known_for_department: "Production",
        name: "Brenda Coxon",
        original_name: "Brenda Coxon",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd19b9251411ea002435d",
        department: "Production",
        job: "Production Accountant",
      },
      {
        adult: false,
        gender: 0,
        id: 1593072,
        known_for_department: "Art",
        name: "Michael Boone",
        original_name: "Michael Boone",
        popularity: 0.98,
        profile_path: null,
        credit_id: "5abcce36c3a3687cb701c5a4",
        department: "Art",
        job: "Assistant Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 1603859,
        known_for_department: "Visual Effects",
        name: "John Evans",
        original_name: "John Evans",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd34a0e0a2609de025c98",
        department: "Visual Effects",
        job: "Special Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1651253,
        known_for_department: "Art",
        name: "Richard Morrison",
        original_name: "Richard Morrison",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef09a80e0a26346dc9eaa2",
        department: "Art",
        job: "Title Designer",
      },
      {
        adult: false,
        gender: 1,
        id: 1700809,
        known_for_department: "Costume & Make-Up",
        name: "Jan Jamison",
        original_name: "Jan Jamison",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccef40e0a2609e1026d8c",
        department: "Costume & Make-Up",
        job: "Hairstylist",
      },
      {
        adult: false,
        gender: 0,
        id: 1712266,
        known_for_department: "Lighting",
        name: "Maurice Gillett",
        original_name: "Maurice Gillett",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1649251411e920248c5",
        department: "Lighting",
        job: "Rigging Gaffer",
      },
      {
        adult: false,
        gender: 2,
        id: 1836071,
        known_for_department: "Crew",
        name: "Roy Clarke",
        original_name: "Roy Clarke",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0b030e0a263878c9eda9",
        department: "Production",
        job: "Production Driver",
      },
      {
        adult: false,
        gender: 2,
        id: 1846759,
        known_for_department: "Lighting",
        name: "Fred Brown",
        original_name: "Fred Brown",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1359251411e9a0238cb",
        department: "Lighting",
        job: "Electrician",
      },
      {
        adult: false,
        gender: 2,
        id: 1978859,
        known_for_department: "Editing",
        name: "Russ Woolnough",
        original_name: "Russ Woolnough",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5e2f0a2b1685da0019e909e5",
        department: "Crew",
        job: "Visual Effects Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 1991276,
        known_for_department: "Production",
        name: "Barbara Kalish",
        original_name: "Barbara Kalish",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccd3c9251411ea3024703",
        department: "Production",
        job: "Associate Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 2010286,
        known_for_department: "Production",
        name: "Chris Kenny",
        original_name: "Chris Kenny",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccd2dc3a3684379025f43",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2010287,
        known_for_department: "Costume & Make-Up",
        name: "Tony Dunsterville",
        original_name: "Tony Dunsterville",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccdf6c3a368435f022ab9",
        department: "Costume & Make-Up",
        job: "Costume Design",
      },
      {
        adult: false,
        gender: 0,
        id: 2010288,
        known_for_department: "Art",
        name: "Jenny Chartres",
        original_name: "Jenny Chartres",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcce289251411e9a023647",
        department: "Art",
        job: "Art Department Assistant",
      },
      {
        adult: false,
        gender: 0,
        id: 2010289,
        known_for_department: "Art",
        name: "Roy Martin",
        original_name: "Roy Martin",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcce800e0a2609db02680d",
        department: "Art",
        job: "Standby Painter",
      },
      {
        adult: false,
        gender: 0,
        id: 2010290,
        known_for_department: "Camera",
        name: "John Campbell",
        original_name: "John Campbell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcce970e0a2609db026825",
        department: "Camera",
        job: "Camera Operator",
      },
      {
        adult: false,
        gender: 0,
        id: 2010291,
        known_for_department: "Camera",
        name: "Stuart Godfrey",
        original_name: "Stuart Godfrey",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccea9c3a3687cb701c608",
        department: "Camera",
        job: "Key Grip",
      },
      {
        adult: false,
        gender: 0,
        id: 2010292,
        known_for_department: "Camera",
        name: "Patricia Gregory",
        original_name: "Patricia Gregory",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccebb9251411ea002410f",
        department: "Camera",
        job: "Grip",
      },
      {
        adult: false,
        gender: 0,
        id: 2010294,
        known_for_department: "Costume & Make-Up",
        name: "Suzanne Reynolds",
        original_name: "Suzanne Reynolds",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccf4b0e0a2609d8029d27",
        department: "Costume & Make-Up",
        job: "Prosthetic Makeup Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2010295,
        known_for_department: "Crew",
        name: "Jamie White",
        original_name: "Jamie White",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccf6d0e0a2609d8029d5b",
        department: "Crew",
        job: "Carpenter",
      },
      {
        adult: false,
        gender: 2,
        id: 2010297,
        known_for_department: "Crew",
        name: "Richard Brierley",
        original_name: "Richard Brierley",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a479251410769b89cf8",
        department: "Camera",
        job: "Clapper Loader",
      },
      {
        adult: false,
        gender: 0,
        id: 2010298,
        known_for_department: "Crew",
        name: "Victor Anderson",
        original_name: "Victor Anderson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abccfb90e0a2609e402567f",
        department: "Crew",
        job: "Propmaker",
      },
      {
        adult: false,
        gender: 0,
        id: 2010303,
        known_for_department: "Sound",
        name: "Paul Smith",
        original_name: "Paul Smith",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd0f60e0a2609db026a49",
        department: "Sound",
        job: "Dialogue Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 2010304,
        known_for_department: "Editing",
        name: "Simon Harris",
        original_name: "Simon Harris",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1090e0a2609de025aa1",
        department: "Editing",
        job: "First Assistant Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 2010306,
        known_for_department: "Production",
        name: "Margaret Adams",
        original_name: "Margaret Adams",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1c1c3a36843620248b7",
        department: "Production",
        job: "Production Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 2010307,
        known_for_department: "Sound",
        name: "John Samworth",
        original_name: "John Samworth",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1dd9251411e9c024469",
        department: "Sound",
        job: "Boom Operator",
      },
      {
        adult: false,
        gender: 1,
        id: 2010308,
        known_for_department: "Sound",
        name: "Paula Connor",
        original_name: "Paula Connor",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1eb9251411ea3024b47",
        department: "Sound",
        job: "Assistant Sound Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 2010309,
        known_for_department: "Sound",
        name: "Rocky Phelan",
        original_name: "Rocky Phelan",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd1f99251411e95025980",
        department: "Sound",
        job: "Foley Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 2010310,
        known_for_department: "Sound",
        name: "Eric Tomlinson",
        original_name: "Eric Tomlinson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd2569251411ea3024b8e",
        department: "Sound",
        job: "Scoring Mixer",
      },
      {
        adult: false,
        gender: 0,
        id: 2010317,
        known_for_department: "Visual Effects",
        name: "Peter Watson",
        original_name: "Peter Watson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd35fc3a368435c026ac1",
        department: "Visual Effects",
        job: "Visual Effects Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 2010318,
        known_for_department: "Production",
        name: "Pat Harrison",
        original_name: "Pat Harrison",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd393c3a36843a6027232",
        department: "Production",
        job: "Unit Manager",
      },
      {
        adult: false,
        gender: 2,
        id: 2029625,
        known_for_department: "Art",
        name: "Michael White",
        original_name: "Michael White",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5ae05f0fc3a3683dd50100dd",
        department: "Art",
        job: "Production Illustrator",
      },
      {
        adult: false,
        gender: 0,
        id: 2067233,
        known_for_department: "Sound",
        name: "John Falcini",
        original_name: "John Falcini",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef09ce925141099fb89bdc",
        department: "Sound",
        job: "Second Assistant Sound",
      },
      {
        adult: false,
        gender: 2,
        id: 2191782,
        known_for_department: "Art",
        name: "Les Benson",
        original_name: "Les Benson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5c28617992514138e1c00c28",
        department: "Art",
        job: "Dressing Prop",
      },
      {
        adult: false,
        gender: 0,
        id: 2230776,
        known_for_department: "Crew",
        name: "Robin Demetriou",
        original_name: "Robin Demetriou",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0adc0e0a264555ca1214",
        department: "Crew",
        job: "Catering",
      },
      {
        adult: false,
        gender: 0,
        id: 2238043,
        known_for_department: "Directing",
        name: "Melvin Lind",
        original_name: "Melvin Lind",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0948925141099fb89aea",
        department: "Directing",
        job: "Second Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2240466,
        known_for_department: "Production",
        name: "Chrissie Richardson",
        original_name: "Chrissie Richardson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0ab70e0a263878c9ed0b",
        department: "Production",
        job: "Assistant Accountant",
      },
      {
        adult: false,
        gender: 0,
        id: 2324786,
        known_for_department: "Costume & Make-Up",
        name: "Tommy Nutter",
        original_name: "Tommy Nutter",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef093bc3a36863ba1e4146",
        department: "Costume & Make-Up",
        job: "Tailor",
      },
      {
        adult: false,
        gender: 0,
        id: 2324787,
        known_for_department: "Directing",
        name: "Steve Millson",
        original_name: "Steve Millson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef095dc3a3685e881e4905",
        department: "Directing",
        job: "Third Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2324788,
        known_for_department: "Art",
        name: "Michael King",
        original_name: "Michael King",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef096e92514109b5b89552",
        department: "Art",
        job: "Construction Buyer",
      },
      {
        adult: false,
        gender: 0,
        id: 2324790,
        known_for_department: "Art",
        name: "Les Andrews",
        original_name: "Les Andrews",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef099a0e0a264146ca1719",
        department: "Art",
        job: "Dressing Prop",
      },
      {
        adult: false,
        gender: 0,
        id: 2324791,
        known_for_department: "Crew",
        name: "Philip Clark",
        original_name: "Philip Clark",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef09e5c3a36863ba1e4285",
        department: "Crew",
        job: "Special Effects Technician",
      },
      {
        adult: false,
        gender: 2,
        id: 2324793,
        known_for_department: "Crew",
        name: "Christian Wolf-La'Moy",
        original_name: "Christian Wolf-La'Moy",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a200e0a261bbbd4c652",
        department: "Crew",
        job: "Stunt Driver",
      },
      {
        adult: false,
        gender: 0,
        id: 2324796,
        known_for_department: "Costume & Make-Up",
        name: "Len Alexander",
        original_name: "Len Alexander",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0a830e0a263878c9ec8c",
        department: "Costume & Make-Up",
        job: "Wardrobe Assistant",
      },
      {
        adult: false,
        gender: 0,
        id: 2324797,
        known_for_department: "Crew",
        name: "Maggie Choyce",
        original_name: "Maggie Choyce",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0ac90e0a263878c9ed16",
        department: "Crew",
        job: "Assistant Script",
      },
      {
        adult: false,
        gender: 0,
        id: 2324799,
        known_for_department: "Crew",
        name: "Terry Shane",
        original_name: "Terry Shane",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0aed0e0a26346dc9ec82",
        department: "Crew",
        job: "Floor Runner",
      },
      {
        adult: false,
        gender: 0,
        id: 2324800,
        known_for_department: "Production",
        name: "Max Brown",
        original_name: "Max Brown",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0b1d0e0a2613cdcb9181",
        department: "Production",
        job: "Production Runner",
      },
      {
        adult: false,
        gender: 0,
        id: 2324801,
        known_for_department: "Visual Effects",
        name: "Janice Body",
        original_name: "Janice Body",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5cef0b280e0a2636a5cb8269",
        department: "Visual Effects",
        job: "Rotoscoping Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 2442990,
        known_for_department: "Acting",
        name: "Ken Barker",
        original_name: "Ken Barker",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5abcd0269251411e9c0242e9",
        department: "Crew",
        job: "Stunts",
      },
    ],
  },
  recommendations: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/7x4SNxO5HWArighxxFeet5sn3il.jpg",
        genre_ids: [28, 14],
        id: 364,
        media_type: "movie",
        title: "Batman Returns",
        original_language: "en",
        original_title: "Batman Returns",
        overview:
          "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman.",
        popularity: 39.759,
        poster_path: "/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
        release_date: "1992-06-19",
        video: false,
        vote_average: 6.84,
        vote_count: 4719,
      },
      {
        adult: false,
        backdrop_path: "/snlu32RmjldF9b068UURJg8sQtn.jpg",
        genre_ids: [28, 80, 14],
        id: 414,
        media_type: "movie",
        title: "Batman Forever",
        original_language: "en",
        original_title: "Batman Forever",
        overview:
          "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.",
        popularity: 27.742,
        poster_path: "/mzzNBVwTiiY94xAXDMWJpNPW2US.jpg",
        release_date: "1995-06-16",
        video: false,
        vote_average: 5.367,
        vote_count: 3897,
      },
      {
        adult: false,
        backdrop_path: "/rpOqHZMNIaI4qP4r7nw1B7oA0mx.jpg",
        genre_ids: [878, 28, 14],
        id: 415,
        media_type: "movie",
        title: "Batman & Robin",
        original_language: "en",
        original_title: "Batman & Robin",
        overview:
          "Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.",
        popularity: 25.974,
        poster_path: "/bsg0mrxUKyJoL4oSGP5mlhEsqp.jpg",
        release_date: "1997-06-20",
        video: false,
        vote_average: 4.309,
        vote_count: 3773,
      },
      {
        adult: false,
        backdrop_path: "/v6MVBFnQOscITvmAy5N5ras2JKZ.jpg",
        genre_ids: [878, 28, 12],
        id: 1924,
        media_type: "movie",
        title: "Superman",
        original_language: "en",
        original_title: "Superman",
        overview:
          "Mild-mannered Clark Kent works as a reporter at the Daily Planet alongside his crush, Lois Lane. Clark must summon his superhero alter-ego when the nefarious Lex Luthor launches a plan to take over the world.",
        popularity: 21.437,
        poster_path: "/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg",
        release_date: "1978-12-13",
        video: false,
        vote_average: 7.084,
        vote_count: 2748,
      },
      {
        adult: false,
        backdrop_path: "/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg",
        genre_ids: [28, 80, 18],
        id: 272,
        media_type: "movie",
        title: "Batman Begins",
        original_language: "en",
        original_title: "Batman Begins",
        overview:
          "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
        popularity: 45.791,
        poster_path: "/1P3ZyEq02wcTMd3iE4ebtLvncvH.jpg",
        release_date: "2005-06-10",
        video: false,
        vote_average: 7.675,
        vote_count: 16458,
      },
      {
        adult: false,
        backdrop_path: "/2hMt6zKQsvYvH3ZRe8T6RzAD2XB.jpg",
        genre_ids: [12, 28],
        id: 87,
        media_type: "movie",
        title: "Indiana Jones and the Temple of Doom",
        original_language: "en",
        original_title: "Indiana Jones and the Temple of Doom",
        overview:
          "After arriving in India, Indiana Jones is asked by a desperate village to find a mystical stone. He agrees – and stumbles upon a secret cult plotting a terrible plan in the catacombs of an ancient palace.",
        popularity: 32.368,
        poster_path: "/5VPmZF77ZjTMqIUQlXZWmdMsGIN.jpg",
        release_date: "1984-05-23",
        video: false,
        vote_average: 7.272,
        vote_count: 6849,
      },
      {
        adult: false,
        backdrop_path: "/267Mdb5i1AXuVN64DhVEOUPmM25.jpg",
        genre_ids: [12, 28],
        id: 89,
        media_type: "movie",
        title: "Indiana Jones and the Last Crusade",
        original_language: "en",
        original_title: "Indiana Jones and the Last Crusade",
        overview:
          "When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana must team up with Marcus Brody, Sallah and Elsa Schneider to follow in his father's footsteps and stop the Nazis from recovering the power of eternal life.",
        popularity: 28.642,
        poster_path: "/sizg1AU8f8JDZX4QIgE4pjUMBvx.jpg",
        release_date: "1989-05-24",
        video: false,
        vote_average: 7.809,
        vote_count: 7523,
      },
      {
        adult: false,
        backdrop_path: "/530hY2IMWWgPInY9AcGtDOLkdQa.jpg",
        genre_ids: [14, 35],
        id: 4011,
        media_type: "movie",
        title: "Beetlejuice",
        original_language: "en",
        original_title: "Beetlejuice",
        overview:
          "Thanks to an untimely demise via drowning, a young couple end up as poltergeists in their New England farmhouse, where they fail to meet the challenge of scaring away the insufferable new owners, who want to make drastic changes. In desperation, the undead newlyweds turn to an expert frightmeister, but he's got a diabolical agenda of his own.",
        popularity: 27.791,
        poster_path: "/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
        release_date: "1988-03-30",
        video: false,
        vote_average: 7.364,
        vote_count: 4873,
      },
      {
        adult: false,
        backdrop_path: "/igaRMweCynEGoS6w4Rsim7JPnKu.jpg",
        genre_ids: [12, 35, 878],
        id: 196,
        media_type: "movie",
        title: "Back to the Future Part III",
        original_language: "en",
        original_title: "Back to the Future Part III",
        overview:
          "The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking for Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More problems arise when Doc falls for pretty schoolteacher Clara Clayton, and Marty tangles with Buford Tannen.",
        popularity: 20.753,
        poster_path: "/crzoVQnMzIrRfHtQw0tLBirNfVg.jpg",
        release_date: "1990-05-25",
        video: false,
        vote_average: 7.434,
        vote_count: 7959,
      },
      {
        adult: false,
        backdrop_path: "/8eRscFbRYl681zDfkjv1jjW1KAA.jpg",
        genre_ids: [878, 28, 12],
        id: 1452,
        media_type: "movie",
        title: "Superman Returns",
        original_language: "en",
        original_title: "Superman Returns",
        overview:
          "Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest to felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.",
        popularity: 31.091,
        poster_path: "/385XwTQZDpRX2d3kxtnpiLrjBXw.jpg",
        release_date: "2006-06-28",
        video: false,
        vote_average: 5.665,
        vote_count: 3180,
      },
      {
        adult: false,
        backdrop_path: "/hZnnUq0mrUQ3e54SJVca4mf2oAQ.jpg",
        genre_ids: [27, 28],
        id: 36647,
        media_type: "movie",
        title: "Blade",
        original_language: "en",
        original_title: "Blade",
        overview:
          'The Daywalker known as "Blade" - a half-vampire, half-mortal man - becomes the protector of humanity against an underground army of vampires.',
        popularity: 25.624,
        poster_path: "/e6ErRnIgKmoBtcKpht3amsMfo52.jpg",
        release_date: "1998-08-21",
        video: false,
        vote_average: 6.698,
        vote_count: 4406,
      },
      {
        adult: false,
        backdrop_path: "/nzs2vnuYolB2dSdX9N8GZ7sz1kP.jpg",
        genre_ids: [878, 28, 12],
        id: 8536,
        media_type: "movie",
        title: "Superman II",
        original_language: "en",
        original_title: "Superman II",
        overview:
          "Three escaped criminals from the planet Krypton test the Man of Steel's mettle. Led by General Zod, the Kryptonians take control of the White House and partner with Lex Luthor to destroy Superman and rule the world. But Superman, who attempts to make himself human in order to get closer to Lois, realizes he has a responsibility to save the planet.",
        popularity: 12.962,
        poster_path: "/jw0tYFCbzjBN8SIhvRC2kdh7pzh.jpg",
        release_date: "1980-12-04",
        video: false,
        vote_average: 6.7,
        vote_count: 1638,
      },
      {
        adult: false,
        backdrop_path: "/fgkgab4Rel0nOI3B3scHeNB4Mn6.jpg",
        genre_ids: [28, 53],
        id: 1573,
        media_type: "movie",
        title: "Die Hard 2",
        original_language: "en",
        original_title: "Die Hard 2",
        overview:
          "Off-duty cop John McClane is gripped with a feeling of déjà vu when, on a snowy Christmas Eve in the nation’s capital, terrorists seize a major international airport, holding thousands of holiday travelers hostage. Renegade military commandos led by a murderous rogue officer plot to rescue a drug lord from justice and are prepared for every contingency except one: McClane’s smart-mouthed heroics.",
        popularity: 22.421,
        poster_path: "/wUEizkONxPZmIWQ2lnMttW0suXH.jpg",
        release_date: "1990-07-02",
        video: false,
        vote_average: 6.883,
        vote_count: 4244,
      },
      {
        adult: false,
        backdrop_path: "/c6yfABGVKuB5cjoOwdX4AJMlzUz.jpg",
        genre_ids: [35, 14],
        id: 620,
        media_type: "movie",
        title: "Ghostbusters",
        original_language: "en",
        original_title: "Ghostbusters",
        overview:
          'After losing their academic posts at a prestigious university, a team of parapsychologists goes into business as proton-pack-toting "ghostbusters" who exterminate ghouls, hobgoblins and supernatural pests of all stripes. An ad campaign pays off when a knockout cellist hires the squad to purge her swanky digs of demons that appear to be living in her refrigerator.',
        popularity: 30.386,
        poster_path: "/5YhJoPzYL9n0ilqDuVO2v89BuYY.jpg",
        release_date: "1984-06-08",
        video: false,
        vote_average: 7.434,
        vote_count: 6617,
      },
      {
        adult: false,
        backdrop_path: "/guTNnSWS3CaH71jasY8W1FMptjG.jpg",
        genre_ids: [12, 28, 35, 53, 80],
        id: 941,
        media_type: "movie",
        title: "Lethal Weapon",
        original_language: "en",
        original_title: "Lethal Weapon",
        overview:
          "Veteran buttoned-down LAPD detective Roger Murtaugh is partnered with unhinged cop Martin Riggs, who -- distraught after his wife's death -- has a death wish and takes unnecessary risks with criminals at every turn. The odd couple embark on their first homicide investigation as partners, involving a young woman known to Murtaugh with ties to a drug and prostitution ring.",
        popularity: 24.89,
        poster_path: "/fTq4ThIP3pQTYR9eDepsbDHqdcs.jpg",
        release_date: "1987-03-06",
        video: false,
        vote_average: 7.254,
        vote_count: 3327,
      },
      {
        adult: false,
        backdrop_path: "/kCiMExsYuNhYluHxPP2OTmWw7hp.jpg",
        genre_ids: [12, 28],
        id: 85,
        media_type: "movie",
        title: "Raiders of the Lost Ark",
        original_language: "en",
        original_title: "Raiders of the Lost Ark",
        overview:
          "When Dr. Indiana Jones – the tweed-suited professor who just happens to be a celebrated archaeologist – is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.",
        popularity: 37.47,
        poster_path: "/awUGN7ZCNq2EUTdpVaHDX23anOZ.jpg",
        release_date: "1981-06-12",
        video: false,
        vote_average: 7.909,
        vote_count: 9351,
      },
      {
        adult: false,
        backdrop_path: "/uw4SnKFZ453Gxmj5XR5Susj8TNo.jpg",
        genre_ids: [28, 12, 878],
        id: 602,
        media_type: "movie",
        title: "Independence Day",
        original_language: "en",
        original_title: "Independence Day",
        overview:
          "On July 2, a giant alien mothership enters orbit around Earth and deploys several dozen saucer-shaped 'destroyer' spacecraft that quickly lay waste to major cities around the planet. On July 3, the United States conducts a coordinated counterattack that fails. On July 4, a plan is devised to gain access to the interior of the alien mothership in space, in order to plant a nuclear missile.",
        popularity: 31.386,
        poster_path: "/p0BPQGSPoSa8Ml0DAf2mB2kCU0R.jpg",
        release_date: "1996-06-25",
        video: false,
        vote_average: 6.833,
        vote_count: 7489,
      },
      {
        adult: false,
        backdrop_path: "/6MQmtWk4cFwSDyNvIgoJRBIHUT3.jpg",
        genre_ids: [14, 28, 12],
        id: 559,
        media_type: "movie",
        title: "Spider-Man 3",
        original_language: "en",
        original_title: "Spider-Man 3",
        overview:
          "The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.",
        popularity: 80.294,
        poster_path: "/2jLxKF73SAPkyhIWrnv67IH7kJ1.jpg",
        release_date: "2007-05-01",
        video: false,
        vote_average: 6.268,
        vote_count: 10043,
      },
      {
        adult: false,
        backdrop_path: "/9hRVHqT4zfdUgfri98TcqJPS2cf.jpg",
        genre_ids: [28, 53, 878],
        id: 5548,
        media_type: "movie",
        title: "RoboCop",
        original_language: "en",
        original_title: "RoboCop",
        overview:
          "In a violent, near-apocalyptic Detroit, evil corporation Omni Consumer Products wins a contract from the city government to privatize the police force. To test their crime-eradicating cyborgs, the company leads street cop Alex Murphy into an armed confrontation with crime lord Boddicker so they can use his body to support their untested RoboCop prototype. But when RoboCop learns of the company's nefarious plans, he turns on his masters.",
        popularity: 23.559,
        poster_path: "/hHtOgGb3NihlyRATHlKPaFApbrd.jpg",
        release_date: "1987-07-17",
        video: false,
        vote_average: 7.25,
        vote_count: 3583,
      },
      {
        adult: false,
        backdrop_path: "/heNbD1JojBNz6kfHWr3O8Uk0a3a.jpg",
        genre_ids: [28, 53, 878],
        id: 296,
        media_type: "movie",
        title: "Terminator 3: Rise of the Machines",
        original_language: "en",
        original_title: "Terminator 3: Rise of the Machines",
        overview:
          "It's been 10 years since John Connor saved Earth from Judgment Day, and he's now living under the radar, steering clear of using anything Skynet can trace. That is, until he encounters T-X, a robotic assassin ordered to finish what T-1000 started. Good thing Connor's former nemesis, the Terminator, is back to aid the now-adult Connor … just like he promised.",
        popularity: 25.529,
        poster_path: "/vvevzdYIrk2636maNW4qeWmlPFG.jpg",
        release_date: "2003-07-02",
        video: false,
        vote_average: 6.108,
        vote_count: 5012,
      },
      {
        adult: false,
        backdrop_path: "/p96949hcwUG2BwE6MgKmw0uYNCx.jpg",
        genre_ids: [12, 28],
        id: 217,
        media_type: "movie",
        title: "Indiana Jones and the Kingdom of the Crystal Skull",
        original_language: "en",
        original_title: "Indiana Jones and the Kingdom of the Crystal Skull",
        overview:
          "Set during the Cold War, the Soviets—led by sword-wielding Irina Spalko—are in search of a crystal skull which has supernatural powers related to a mystical Lost City of Gold. Indy is coerced to head to Peru at the behest of a young man whose friend—and Indy's colleague—Professor Oxley has been captured for his knowledge of the skull's whereabouts.",
        popularity: 26.979,
        poster_path: "/56As6XEM1flWvprX4LgkPl8ii4K.jpg",
        release_date: "2008-05-21",
        video: false,
        vote_average: 5.95,
        vote_count: 6231,
      },
    ],
    total_pages: 2,
    total_results: 40,
  },
};

export default movieDetails;
